# Auto deploy to OSS

name: deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: npm install
      run: npm install
    - name: npm build
      run: npm run build
    - name: Setup Aliyun OSS
      uses: manyuanrong/setup-ossutil@master
      with:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        access-key-id: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
        access-key-secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
    - name: Delete Old assets
      run: ossutil rm -rf oss://njsc-fe/aauth/
    - name: Upload files to OSS
      run: ossutil cp -rf ./dist oss://njsc-fe/aauth/
